### ISSUE TITLE
nest is returning interfered result in thin

### ISSUE THREAD

**Issue by phuongnd08** [soveran/nest#11]
nest.get is returning result of different redis query (like a redis set, or of different key) when running in thin.

When I switch from nest to the regular redis-rb, the issue go away.

**Comment by phuongnd08** [comment]
I guess this is the issue of redic. We are thinking about stacking nest on top of redis instead of the unsafe redic?

**Comment by soveran** [comment]
Can you show me code that replicates the error?

**Comment by phuongnd08** [comment]
It will be a bit costly for me to get a reproduce sample. May take a while.

**Comment by phuongnd08** [comment]
I forked nest to change the underlying redic to `redis` instead. New redis version also feature the "call" command so it works seamlessly. So far I don't experience any interfering result with nest-redis as in nest redic.

**Comment by phuongnd08** [comment]
This is the fork https://github.com/remitano/nest-redis

**Comment by soveran** [comment]
Hello @phuongnd08, any hint on how I can reproduce the error with Redic?
