### ISSUE TITLE
addition of method_missing without to_ary breaks ohm

### ISSUE THREAD

**Issue by slowernet** [soveran/nest#9]
A test app with ohm 3.1.1 and nest 3.1.0 (ruby 2.3.1p112) fails on Ohm::Model#find:

```
TypeError: can't convert Nest to Array (Nest#to_ary gives RuntimeError)
	ohm-3.1.1/lib/ohm.rb:1480:in `flatten'
```

This may be related to an interaction between `method_missing` and `flatten` discussed [here](https://tenderlovemaking.com/2011/06/28/til-its-ok-to-return-nil-from-to_ary.html). I did not write tests, but cargo-culting the [solution](https://github.com/bundler/bundler/pull/1274) applied to bundler there also appeared to solve the problem for nest:

```
private
def to_ary
  nil
end
```

Thanks!

**Comment by soveran** [comment]
rr

**Comment by soveran** [comment]
@slowernet Great job investigating this issue! I was completely unaware and made the mistake of releasing Nest without checking if Ohm was working fine. Thanks a lot!
